print("Hello Monday")
print("Hello Monday")
print(" looks good awesome doing great")
print(" looks good awesome doing great")
print("Ade is good to be true")
print("Ade is good to be true let me know now")
print("Hello Tuesday")
print("Hello Wednesday")
print("Hello Thursday")
print("Ade is good to be true")
print("I need to be sure am good to go")
print("Ola is a superstar")
print("Hello Friday")
print("Hello Friday is a good day")
print("Hello Saturday")
print("Able God of mercy")
print("Able God of mercy of goodness and mercies")
print("Hello Saturday is a great day")
