print("Hello Monday")
print("Hello Monday")
print(" looks good awesome doing great")
print(" looks good awesome doing great")
print("Ade is good to be true")
print("Ade is good to be true let me know now")
print("Hello Tuesday")
print("Hello Wenesday")
print("Hello Thursday")
